create table notes(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  note_name TEXT NOT NULL,
  description text not null,
  modified_date date DEFAULT now(),
  folder_id INTEGER REFERENCES folders(id) ON DELETE CASCADE NOT NULL
  );